
name: Create Issue From File Example Command
on:
  workflow_dispatch:
jobs:
  createIssues:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Create Issue 1 From File
      id: step1
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Create database table for CollegiateSubreddits
        content-filepath: issues/issue01_create_database_table copy.md
    - name: Add Issue 1 to Kanban board My Project
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: My Project
        column-name: Todo
        issue-number: ${{ steps.step1.outputs.issue-number }}

    - uses: actions/checkout@v2
    - name: Create Issue 2 From File
      id: step2
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Create database table for CollegiateSubreddits
        content-filepath: issues/issue02_add_list_all_and_post_endpoints.md
    - name: Add Issue 2 to Kanban board My Project
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: My Project
        column-name: Todo
        issue-number: ${{ steps.step2.outputs.issue-number }}
