
name: Create Issue From File Example Command
on:
  workflow_dispatch:
jobs:
  createIssues:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Create database table for CollegiateSubreddits
        content-filepath: issues/issue01_create_database_table copy.md
    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: My Project
        column-name: Todo
        issue-number: ${{ steps.ciff.outputs.issue-number }}

    - uses: actions/checkout@v2
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Create database table for CollegiateSubreddits
        content-filepath: issues/issue02_add_list_all_and_post_endpoints.md
    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: My Project
        column-name: Todo
        issue-number: ${{ steps.ciff.outputs.issue-number }}
